
#' Convert symbol to Wormbase ID
#'
#' @param symbol gene symbols.
#' @param geneIDs Translation table generated with `load_gene_ids()`.
#'
#' @return The corresponding Wormbase IDs.
#' @export
#'
#' @examples
#' gids <- wb_load_gene_ids("WS277")
#' s2i("unc-10", gids)
s2i <- function(symbol, geneIDs){
  geneIDs$gene_id[match(symbol, geneIDs$name)]
  }


#' Convert Wormbase ID to symbol
#'
#' @param gene_id Wormbase gene IDs
#' @param geneIDs Translation table generated by `load_gene_ids()`.
#'
#' @return The corresponding gene symbols. If a gene symbol is missing, the sequence
#' name is returned instead.
#' @export
#'
#' @examples
#' gids <- wb_load_gene_ids("WS277")
#' s2i("unc-10", gids)
i2s <- function(gene_id, geneIDs){
  geneIDs$name[match(gene_id, geneIDs$gene_id)]
}
